//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wonderthing.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEightBall")]
    public interface IEightBall {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/ObtainAnswerToQuestion", ReplyAction="http://tempuri.org/IEightBall/ObtainAnswerToQuestionResponse")]
        string ObtainAnswerToQuestion(string userQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/ObtainAnswerToQuestion", ReplyAction="http://tempuri.org/IEightBall/ObtainAnswerToQuestionResponse")]
        System.Threading.Tasks.Task<string> ObtainAnswerToQuestionAsync(string userQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/ProcessPhoto", ReplyAction="http://tempuri.org/IEightBall/ProcessPhotoResponse")]
        byte[] ProcessPhoto(byte[] bytes, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/ProcessPhoto", ReplyAction="http://tempuri.org/IEightBall/ProcessPhotoResponse")]
        System.Threading.Tasks.Task<byte[]> ProcessPhotoAsync(byte[] bytes, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/DownloadAndProcessPhoto", ReplyAction="http://tempuri.org/IEightBall/DownloadAndProcessPhotoResponse")]
        byte[] DownloadAndProcessPhoto(string url, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/DownloadAndProcessPhoto", ReplyAction="http://tempuri.org/IEightBall/DownloadAndProcessPhotoResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadAndProcessPhotoAsync(string url, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEightBallChannel : Wonderthing.ServiceReference1.IEightBall, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EightBallClient : System.ServiceModel.ClientBase<Wonderthing.ServiceReference1.IEightBall>, Wonderthing.ServiceReference1.IEightBall {
        
        public EightBallClient() {
        }
        
        public EightBallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EightBallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtainAnswerToQuestion(string userQuestion) {
            return base.Channel.ObtainAnswerToQuestion(userQuestion);
        }
        
        public System.Threading.Tasks.Task<string> ObtainAnswerToQuestionAsync(string userQuestion) {
            return base.Channel.ObtainAnswerToQuestionAsync(userQuestion);
        }
        
        public byte[] ProcessPhoto(byte[] bytes, string name) {
            return base.Channel.ProcessPhoto(bytes, name);
        }
        
        public System.Threading.Tasks.Task<byte[]> ProcessPhotoAsync(byte[] bytes, string name) {
            return base.Channel.ProcessPhotoAsync(bytes, name);
        }
        
        public byte[] DownloadAndProcessPhoto(string url, string id) {
            return base.Channel.DownloadAndProcessPhoto(url, id);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadAndProcessPhotoAsync(string url, string id) {
            return base.Channel.DownloadAndProcessPhotoAsync(url, id);
        }
    }
}
